$ANSIBLE_VAULT;1.1;AES256
61303964333539366234646133303965656365363134646562613233643831653531613631356235
3234363030623936396332366164373562616333396339660a633532383935663339613635646230
64626233656337343539343136393133363633613866633532613239373932636135336339343034
3666343739386461610a666366326533663935616530376430346265613763383931643534663636
32613764643637623931373661343937643134313535663231306333323063643863323136306463
36303635616133343239623734636438626130646563353537623631653861656532653037616131
34346536623839343365336361323066316439323832616532616263666562323833356631393466
62353763633534303565646231383531313232653864653433306139653663613065343866323861
32343539653535336239623130656366396536346136383265383637343062613363653234346263
30646463626632323165616163383966326561373863306135393762323032306533326539373130
633030393637376235643437386537306337
